global:
  scrape_interval: "5s"
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: grafana
    static_configs:
      - targets:
          - "grafana:3000"
  - job_name: alertmanager
    static_configs:
      - targets:
          - "alertmanager:9093"
  - job_name: node-exporter
    static_configs:
      - targets:
          - "node-exporter:9100"
