name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: E2E test
        run: make e2e-test
