name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: E2E test
        run: make e2e-test

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --rm-dist
